/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.webbe;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DJQE {
    private static final Logger logger = LoggerFactory.getLogger(DJQE.class);

    public static void main(String[] args) {
        logger.info("Starting Distributed Task Queue");
        // Main application logic will go here
    }
}
